import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";



export const metadata: Metadata = {
  title: "Real POS Light",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en h-full">
      <body
        className={`antialiased`}
      >
        {children}
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
